using System;
using System.Collections.Generic;
using System.Text;

namespace ApiControlAcceso.MODELS.Models
{
    public class Site
    {
        public int SiteId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public int AlarmStatusPage { get; set; }
        public int EventWindow1 { get; set; }
        public int EventWindow2 { get; set; }
        public int EventWindow3 { get; set; }
        public int EventWindow4 { get; set; }
        public int EventWindow5 { get; set; }
        public int EventWindow6 { get; set; }
        public DateTime LastModified { get; set; }
        public bool LastModifiedValid { get; set; }
        public bool DisplayPredefinedCustomerFieldsinUsers { get; set; }
        public bool ImportUsersFromActiveDirectory { get; set; }
        public string WindowsGroup { get; set; }
        public DateTime Created { get; set; }
        public string LastOperator { get; set; }
        public string ActiveDirectoryDomain { get; set; }
        public int ControllerType { get; set; }
        public int DefaultFloorPlan { get; set; }
        public int DefaultStatusPage { get; set; }
        public string OrganizationName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Addess3 { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string WebSite { get; set; }
        public string Email { get; set; }
        public bool EnableSupremaIntegration { get; set; }
        public string DefaultFacilityNumber { get; set; }
        public int DefaultEnrollmentReader { get; set; }
        public string AccessLevelAttribute { get; set; }
        public string CardNumberAttribute { get; set; }
        public int AccessLevelAttributeMap { get; set; }
        public int CardNumberAttributeMap { get; set; }
        public bool EnableSaltoIntegration { get; set; }
        public string Ipaddress { get; set; }
        public int Ipport { get; set; }
        public int LastEventId { get; set; }
        public string DefaultSaltoEncoder { get; set; }
        public string MifareAkey { get; set; }
        public string MifareBkey { get; set; }
        public string MasterKey { get; set; }
        public bool DisableAdusers { get; set; }
        public bool Sector0 { get; set; }
        public bool Sector1 { get; set; }
        public bool Sector2 { get; set; }
        public bool Sector3 { get; set; }
        public bool Sector4 { get; set; }
        public bool Sector5 { get; set; }
        public bool Sector6 { get; set; }
        public bool Sector7 { get; set; }
        public bool Sector8 { get; set; }
        public bool Sector9 { get; set; }
        public bool Sector10 { get; set; }
        public bool Sector11 { get; set; }
        public bool Sector12 { get; set; }
        public bool Sector13 { get; set; }
        public bool Sector14 { get; set; }
        public bool Sector15 { get; set; }
        public bool Sector4k0 { get; set; }
        public bool Sector4k1 { get; set; }
        public bool Sector4k2 { get; set; }
        public bool Sector4k3 { get; set; }
        public bool Sector4k4 { get; set; }
        public bool Sector4k5 { get; set; }
        public bool Sector4k6 { get; set; }
        public bool Sector4k7 { get; set; }
        public bool Sector4k8 { get; set; }
        public bool Sector4k9 { get; set; }
        public bool Sector4k10 { get; set; }
        public bool Sector4k11 { get; set; }
        public bool Sector4k12 { get; set; }
        public bool Sector4k13 { get; set; }
        public bool Sector4k14 { get; set; }
        public bool Sector4k15 { get; set; }
        public bool Sector4k16 { get; set; }
        public bool Sector4k17 { get; set; }
        public bool Sector4k18 { get; set; }
        public bool Sector4k19 { get; set; }
        public bool Sector4k20 { get; set; }
        public bool Sector4k21 { get; set; }
        public bool Sector4k22 { get; set; }
        public bool Sector4k23 { get; set; }
        public bool Sector4k24 { get; set; }
        public bool Sector4k25 { get; set; }
        public bool Sector4k26 { get; set; }
        public bool Sector4k27 { get; set; }
        public bool Sector4k28 { get; set; }
        public bool Sector4k29 { get; set; }
        public bool Sector4k30 { get; set; }
        public bool Sector4k31 { get; set; }
        public bool Sector4k32 { get; set; }
        public bool Sector4k33 { get; set; }
        public bool Sector4k34 { get; set; }
        public bool Sector4k35 { get; set; }
        public bool Sector4k36 { get; set; }
        public bool Sector4k37 { get; set; }
        public bool Sector4k38 { get; set; }
        public bool Sector4k39 { get; set; }
        public bool Spare { get; set; }
        public bool EnableKabaIntegration { get; set; }
        public string KabaCenTranInputPath { get; set; }
        public string KabaCenTranOutputPath { get; set; }
        public string KabaDispatcherId { get; set; }
        public string KabaBranchName { get; set; }
        public bool? LogAllTransaction { get; set; }
        public int KabaSynchInterval { get; set; }
        public int KabaCommandTimeout { get; set; }
        public bool EnableSaltoLogging { get; set; }
        public bool SaltoSynchronised { get; set; }
        public bool DefaultUserStartDateValid { get; set; }
        public DateTime DefaultUserStartDate { get; set; }
        public bool DefaultUserExpiryDateValid { get; set; }
        public DateTime DefaultUserExpiryDate { get; set; }
        public bool DisplayUsersInGroup { get; set; }
        public bool? CalendarActionsVisibility { get; set; }
        public bool? DisableAdusersDeleted { get; set; }
        public int AdsyncPeriod { get; set; }
        public bool? EnableKwintegration { get; set; }
        public string Kwipaddress { get; set; }
        public int Kwipport { get; set; }
        public int KwsyncInterval { get; set; }
        public bool? EnableKwlogging { get; set; }
        public int KeyWatcherUserIddigitLength { get; set; }
        public int SitePhotoPlaceHolderWidthPixels { get; set; }
        public int SitePhotoPlaceHolderHeightPixels { get; set; }
        public int DefaultUsersInactivityPeriodInMinutes { get; set; }
        public bool DefaultUsersInactivityPeriodIsActive { get; set; }
        public int DefaultUsersInactivityPeriodAction { get; set; }
        public bool ApplyEnhancedSecurity { get; set; }
        public bool? EnhancedSecDenyPinDuplicate { get; set; }
        public bool EnhancedSecOnlyKeypad { get; set; }
        public int DefaultSiteUsersInactivityPeriodInMinutes { get; set; }
        public bool DefaultSiteUsersInactivityPeriodIsActive { get; set; }
        public int DefaultSiteUsersInactivityPeriodAction { get; set; }
        public int DefaultSiteUsersInactivityDeletionPeriodInMinutes { get; set; }
        public bool DefaultSiteUsersInactivityDeletionPeriodIsActive { get; set; }
        public int DefaultSiteUsersInactivityDeletionPeriodAction { get; set; }
        public int ScheduleType { get; set; }
        public DateTime OneTimeStartTime { get; set; }
        public int Occurs { get; set; }
        public int EveryDayOfYear { get; set; }
        public int EveryWeek { get; set; }
        public int EveryDayOfMonth { get; set; }
        public int EveryMonth { get; set; }
        public int EveryMonth2 { get; set; }
        public bool Monday { get; set; }
        public bool Tuesday { get; set; }
        public bool Wednesday { get; set; }
        public bool Thursday { get; set; }
        public bool Friday { get; set; }
        public bool Saturday { get; set; }
        public bool Sunday { get; set; }
        public int Monthly { get; set; }
        public int WeekOfMonth { get; set; }
        public int Weekday { get; set; }
        public int DailyFrequency { get; set; }
        public int PeriodType { get; set; }
        public int PeriodHour { get; set; }
        public int PeriodMinute { get; set; }
        public DateTime StartingAt { get; set; }
        public DateTime StartingAt2 { get; set; }
        public DateTime EndingAt { get; set; }
        public bool? Duration { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string ExportFolder { get; set; }
        public int ExportFormat { get; set; }
        public int FileNameCustomFieldId { get; set; }
        public bool? ExportEnabled { get; set; }
        public int ExportLastRunStatus { get; set; }
        public DateTime ExportLastRunTime { get; set; }
        public DateTime ExportNextRunTime { get; set; }
        public bool ExportStartedAtLeastOnce { get; set; }
        public int PinComplexity { get; set; }
        public int PinExpiryTime { get; set; }
        public int MinimumPinlength { get; set; }
        public int MaximumSequentialDigitsInPin { get; set; }
        public int MaximumRepeativeDigitsInPin { get; set; }
        public bool NewPintobeGeneratedBySystem { get; set; }
        public bool ShowControllerOnlineStabilityBar { get; set; }
        public int DefaultPinlength { get; set; }
        public bool IncreaseCardPrintTimes { get; set; }
        public bool EnablePrincetonIntegration { get; set; }
        public string PrincetonDefaultFacilityNumber { get; set; }
        public int PrincetonDefaultEnrollmentReader { get; set; }
        public string PrincetonIdentityIpaddress { get; set; }
        public int PrincetonIdentityIpport { get; set; }
        public string PrincetonIdentityUsername { get; set; }
        public string PrincetonIdentityPassword { get; set; }
        public int PrincetonCredentialType { get; set; }
    }
}
