using System;
using System.Collections.Generic;
using System.Text;

namespace ApiControlAcceso.MODELS.Models
{
    public class User
    {
        public int UserId { get; set; }
        public int SiteId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Name { get; set; }
        public string Name2 { get; set; }
        public int UserAccessLevel { get; set; }
        public DateTime LastModified { get; set; }
        public bool LastModifiedValid { get; set; }
        public bool? Showagreetingmessagetouser { get; set; }
        public bool GoDirectlyToTheMenuOnLogin { get; set; }
        public bool UserCanAcknowledgeAlarmMemory { get; set; }
        public bool ShowAlarmMemoryOnLogin { get; set; }
        public bool TurnOffthePrimaryAreaIfUserHasAccessOnLogin { get; set; }
        public bool TurnOfftheUserAreaonLoginifUserhasaccess { get; set; }
        public bool AcknowledgeSystemTroubles { get; set; }
        public bool Userhassuperrightsandcanoverrideantipassback { get; set; }
        public bool UserCanModifyTheirOwnCode { get; set; }
        public bool UserOperatesAdafunction { get; set; }
        public bool UserLoiterExpiryCountEnabled { get; set; }
        public bool UserCanLogInRemotely { get; set; }
        public bool UserisaDuressUser { get; set; }
        public DateTime ExpiryDate { get; set; }
        public DateTime ExpiryTime { get; set; }
        public int DoorGroupException { get; set; }
        public string Pinnumber { get; set; }
        public int UserCardNumber { get; set; }
        public int ImageId { get; set; }
        public bool Merge { get; set; }
        public bool DisableUser { get; set; }
        public bool TraceUser { get; set; }
        public string BadgeNumber { get; set; }
        public string BadgeType { get; set; }
        public string ServiceName { get; set; }
        public string ServiceNumber { get; set; }
        public string EmployeeFunction { get; set; }
        public string LicenseNumber { get; set; }
        public string Union { get; set; }
        public string Site { get; set; }
        public DateTime DateOfBadgeProduction { get; set; }
        public DateTime ExpirationDateOfBadge { get; set; }
        public string CustomField1 { get; set; }
        public string CustomField2 { get; set; }
        public string CustomField3 { get; set; }
        public string CustomField4 { get; set; }
        public string CustomField5 { get; set; }
        public string CustomNoteField1 { get; set; }
        public string CustomNoteField2 { get; set; }
        public string CardNumber { get; set; }
        public string CardType { get; set; }
        public int DefaultLanguage { get; set; }
        public int PhotoIdtemplate { get; set; }
        public bool RearmAreaInStayMode { get; set; }
        public int UserArea { get; set; }
        public int UserAreaGroup { get; set; }
        public int RecordGroup { get; set; }
        public bool ExternallyManaged { get; set; }
        public string ExternalData { get; set; }
        public int Image2Id { get; set; }
        public bool ExpiryDateValid { get; set; }
        public DateTime StartDate { get; set; }
        public bool StartDateValid { get; set; }
        public DateTime Created { get; set; }
        public string LastOperator { get; set; }
        public bool DualCustodyMaster { get; set; }
        public bool DualCustodyProvider { get; set; }
        public int Seindex { get; set; }
        public bool? Finger1 { get; set; }
        public bool Duress1 { get; set; }
        public string FingerData { get; set; }
        public bool Finger2 { get; set; }
        public bool Duress2 { get; set; }
        public string FingerData2 { get; set; }
        public int BiometricData1 { get; set; }
        public bool EnableSupremaIntegration { get; set; }
        public int EnrollmentDevice { get; set; }
        public int Calendar { get; set; }
        public bool UseExtendedOpeningTime { get; set; }
        public bool OverridePrivacy { get; set; }
        public bool OverrideLockdown { get; set; }
        public bool Office { get; set; }
        public bool UseAntipassback { get; set; }
        public bool? AuditOpeningsInTheKey { get; set; }
        public bool Pin { get; set; }
        public bool UserExpires { get; set; }
        public DateTime UserActivation { get; set; }
        public bool? EnableRevalidationOfKeyExpiration { get; set; }
        public int UpdatePeriod { get; set; }
        public int DaysOrHours { get; set; }
        public bool Salto { get; set; }
        public int UserSaltoDoor { get; set; }
        public int UserSaltoDoorGroup { get; set; }
        public int UserSaltoOutput { get; set; }
        public DateTime UserExpiryDate { get; set; }
        public bool ExternallyManaged2 { get; set; }
        public string ExternalData2 { get; set; }
        public DateTime SaltoKeyValidUntil { get; set; }
        public string KeyAssigned { get; set; }
        public string SaltoKeyData { get; set; }
        public bool SupportsVms { get; set; }
        public int VisitorAccessLevel { get; set; }
        public bool VisitorCard { get; set; }
        public int VisitorNotificationMode { get; set; }
        public string NotificationAddress { get; set; }
        public int VmscardIndex { get; set; }
        public int VmstemplateId { get; set; }
        public int UserRoom { get; set; }
        public string SalaryNumber { get; set; }
        public DateTime VmsexpectedLeaveDate { get; set; }
        public int Vmsstatus { get; set; }
        public DateTime VmscheckedIn { get; set; }
        public DateTime VmscheckedOut { get; set; }
        public bool DisabledVisitorCard { get; set; }
        public int ReportingId { get; set; }
        public int UserKabaLock { get; set; }
        public int UserKabaLockGroup { get; set; }
        public bool KabaKeyInitialised { get; set; }
        public int KabaBankUserId { get; set; }
        public string KabaKeyId { get; set; }
        public bool KabaPinchanged { get; set; }
        public bool SaltoOverridePrivacy { get; set; }
        public bool SaltoOverrideLockdown { get; set; }
        public bool SaltoLockdownEnabled { get; set; }
        public bool TreatUserPinless1AsDuress { get; set; }
        public bool? LegacyPhotoIdDisplayMode { get; set; }
        public bool CodeCanArmSystemOnly { get; set; }
        public bool UserCanModifyOtherUsers { get; set; }
        public bool DisarmOnSingleBadgeEnabled { get; set; }
        public bool ArmOn3BadgeEnabled { get; set; }
        public bool Badge3LatchDoorToggle { get; set; }
        public bool Badge3LatchDoor2Hours { get; set; }
        public bool Badge3LatchDoor4Hours { get; set; }
        public bool Badge3LatchDoor8Hours { get; set; }
        public int UserKeyWatcherId { get; set; }
        public bool HliisVipuser { get; set; }
        public bool HlienableVertigo { get; set; }
        public bool HlienableSplitGroup { get; set; }
        public bool HlienableVertigo2 { get; set; }
        public bool HlienableCartService { get; set; }
        public bool HlienableCimoverride { get; set; }
        public int UserPhotoPlaceHolderWidthPixels { get; set; }
        public int UserPhotoPlaceHolderHeightPixels { get; set; }
        public byte UserType { get; set; }
        public int UserInactivityPeriodInMinutes { get; set; }
        public bool UserInactivityPeriodIsActive { get; set; }
        public int UserInactivityPeriodAction { get; set; }
        public DateTime UserLastActive { get; set; }
        public int UserInactivityDeletionPeriodInMinutes { get; set; }
        public bool UserInactivityDeletionPeriodIsActive { get; set; }
        public int UserInactivityDeletionPeriodAction { get; set; }
        public bool UserLastActiveValid { get; set; }
        public DateTime LastPinUpdate { get; set; }
        public int PinexpiryTimeOnUser { get; set; }
        public string BiometricFaceData { get; set; }
    }
}
